// nios.v

// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module nios (
		input  wire        clk_clk,                          //                       clk.clk
		input  wire        i2c_camera_i2c_serial_sda_in,     //     i2c_camera_i2c_serial.sda_in
		input  wire        i2c_camera_i2c_serial_scl_in,     //                          .scl_in
		output wire        i2c_camera_i2c_serial_sda_oe,     //                          .sda_oe
		output wire        i2c_camera_i2c_serial_scl_oe,     //                          .scl_oe
		input  wire        i2c_hdmi_tx_i2c_serial_sda_in,    //    i2c_hdmi_tx_i2c_serial.sda_in
		input  wire        i2c_hdmi_tx_i2c_serial_scl_in,    //                          .scl_in
		output wire        i2c_hdmi_tx_i2c_serial_sda_oe,    //                          .sda_oe
		output wire        i2c_hdmi_tx_i2c_serial_scl_oe,    //                          .scl_oe
		output wire [31:0] pio_0_external_connection_export, // pio_0_external_connection.export
		input  wire        reset_reset_n                     //                     reset.reset_n
	);

	wire  [31:0] master_0_master_readdata;                              // mm_interconnect_0:master_0_master_readdata -> master_0:master_readdata
	wire         master_0_master_waitrequest;                           // mm_interconnect_0:master_0_master_waitrequest -> master_0:master_waitrequest
	wire  [31:0] master_0_master_address;                               // master_0:master_address -> mm_interconnect_0:master_0_master_address
	wire         master_0_master_read;                                  // master_0:master_read -> mm_interconnect_0:master_0_master_read
	wire   [3:0] master_0_master_byteenable;                            // master_0:master_byteenable -> mm_interconnect_0:master_0_master_byteenable
	wire         master_0_master_readdatavalid;                         // mm_interconnect_0:master_0_master_readdatavalid -> master_0:master_readdatavalid
	wire         master_0_master_write;                                 // master_0:master_write -> mm_interconnect_0:master_0_master_write
	wire  [31:0] master_0_master_writedata;                             // master_0:master_writedata -> mm_interconnect_0:master_0_master_writedata
	wire  [31:0] mm_interconnect_0_sysid_qsys_0_control_slave_readdata; // sysid_qsys_0:readdata -> mm_interconnect_0:sysid_qsys_0_control_slave_readdata
	wire   [0:0] mm_interconnect_0_sysid_qsys_0_control_slave_address;  // mm_interconnect_0:sysid_qsys_0_control_slave_address -> sysid_qsys_0:address
	wire  [31:0] mm_interconnect_0_i2c_camera_csr_readdata;             // i2c_Camera:readdata -> mm_interconnect_0:i2c_Camera_csr_readdata
	wire   [3:0] mm_interconnect_0_i2c_camera_csr_address;              // mm_interconnect_0:i2c_Camera_csr_address -> i2c_Camera:addr
	wire         mm_interconnect_0_i2c_camera_csr_read;                 // mm_interconnect_0:i2c_Camera_csr_read -> i2c_Camera:read
	wire         mm_interconnect_0_i2c_camera_csr_write;                // mm_interconnect_0:i2c_Camera_csr_write -> i2c_Camera:write
	wire  [31:0] mm_interconnect_0_i2c_camera_csr_writedata;            // mm_interconnect_0:i2c_Camera_csr_writedata -> i2c_Camera:writedata
	wire  [31:0] mm_interconnect_0_i2c_hdmi_tx_csr_readdata;            // i2c_hdmi_tx:readdata -> mm_interconnect_0:i2c_hdmi_tx_csr_readdata
	wire   [3:0] mm_interconnect_0_i2c_hdmi_tx_csr_address;             // mm_interconnect_0:i2c_hdmi_tx_csr_address -> i2c_hdmi_tx:addr
	wire         mm_interconnect_0_i2c_hdmi_tx_csr_read;                // mm_interconnect_0:i2c_hdmi_tx_csr_read -> i2c_hdmi_tx:read
	wire         mm_interconnect_0_i2c_hdmi_tx_csr_write;               // mm_interconnect_0:i2c_hdmi_tx_csr_write -> i2c_hdmi_tx:write
	wire  [31:0] mm_interconnect_0_i2c_hdmi_tx_csr_writedata;           // mm_interconnect_0:i2c_hdmi_tx_csr_writedata -> i2c_hdmi_tx:writedata
	wire         mm_interconnect_0_pio_0_s1_chipselect;                 // mm_interconnect_0:pio_0_s1_chipselect -> pio_0:chipselect
	wire  [31:0] mm_interconnect_0_pio_0_s1_readdata;                   // pio_0:readdata -> mm_interconnect_0:pio_0_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_0_s1_address;                    // mm_interconnect_0:pio_0_s1_address -> pio_0:address
	wire         mm_interconnect_0_pio_0_s1_write;                      // mm_interconnect_0:pio_0_s1_write -> pio_0:write_n
	wire  [31:0] mm_interconnect_0_pio_0_s1_writedata;                  // mm_interconnect_0:pio_0_s1_writedata -> pio_0:writedata
	wire         rst_controller_reset_out_reset;                        // rst_controller:reset_out -> [i2c_Camera:rst_n, i2c_hdmi_tx:rst_n, mm_interconnect_0:master_0_clk_reset_reset_bridge_in_reset_reset, mm_interconnect_0:sysid_qsys_0_reset_reset_bridge_in_reset_reset, pio_0:reset_n, sysid_qsys_0:reset_n]
	wire         master_0_master_reset_reset;                           // master_0:master_reset_reset -> [rst_controller:reset_in1, rst_controller_001:reset_in1]
	wire         rst_controller_001_reset_out_reset;                    // rst_controller_001:reset_out -> master_0:clk_reset_reset

	altera_avalon_i2c #(
		.USE_AV_ST       (0),
		.FIFO_DEPTH      (32),
		.FIFO_DEPTH_LOG2 (5)
	) i2c_camera (
		.clk       (clk_clk),                                    //            clock.clk
		.rst_n     (~rst_controller_reset_out_reset),            //       reset_sink.reset_n
		.intr      (),                                           // interrupt_sender.irq
		.addr      (mm_interconnect_0_i2c_camera_csr_address),   //              csr.address
		.read      (mm_interconnect_0_i2c_camera_csr_read),      //                 .read
		.write     (mm_interconnect_0_i2c_camera_csr_write),     //                 .write
		.writedata (mm_interconnect_0_i2c_camera_csr_writedata), //                 .writedata
		.readdata  (mm_interconnect_0_i2c_camera_csr_readdata),  //                 .readdata
		.sda_in    (i2c_camera_i2c_serial_sda_in),               //       i2c_serial.sda_in
		.scl_in    (i2c_camera_i2c_serial_scl_in),               //                 .scl_in
		.sda_oe    (i2c_camera_i2c_serial_sda_oe),               //                 .sda_oe
		.scl_oe    (i2c_camera_i2c_serial_scl_oe),               //                 .scl_oe
		.src_data  (),                                           //      (terminated)
		.src_valid (),                                           //      (terminated)
		.src_ready (1'b0),                                       //      (terminated)
		.snk_data  (16'b0000000000000000),                       //      (terminated)
		.snk_valid (1'b0),                                       //      (terminated)
		.snk_ready ()                                            //      (terminated)
	);

	altera_avalon_i2c #(
		.USE_AV_ST       (0),
		.FIFO_DEPTH      (32),
		.FIFO_DEPTH_LOG2 (5)
	) i2c_hdmi_tx (
		.clk       (clk_clk),                                     //            clock.clk
		.rst_n     (~rst_controller_reset_out_reset),             //       reset_sink.reset_n
		.intr      (),                                            // interrupt_sender.irq
		.addr      (mm_interconnect_0_i2c_hdmi_tx_csr_address),   //              csr.address
		.read      (mm_interconnect_0_i2c_hdmi_tx_csr_read),      //                 .read
		.write     (mm_interconnect_0_i2c_hdmi_tx_csr_write),     //                 .write
		.writedata (mm_interconnect_0_i2c_hdmi_tx_csr_writedata), //                 .writedata
		.readdata  (mm_interconnect_0_i2c_hdmi_tx_csr_readdata),  //                 .readdata
		.sda_in    (i2c_hdmi_tx_i2c_serial_sda_in),               //       i2c_serial.sda_in
		.scl_in    (i2c_hdmi_tx_i2c_serial_scl_in),               //                 .scl_in
		.sda_oe    (i2c_hdmi_tx_i2c_serial_sda_oe),               //                 .sda_oe
		.scl_oe    (i2c_hdmi_tx_i2c_serial_scl_oe),               //                 .scl_oe
		.src_data  (),                                            //      (terminated)
		.src_valid (),                                            //      (terminated)
		.src_ready (1'b0),                                        //      (terminated)
		.snk_data  (16'b0000000000000000),                        //      (terminated)
		.snk_valid (1'b0),                                        //      (terminated)
		.snk_ready ()                                             //      (terminated)
	);

	nios_master_0 #(
		.USE_PLI     (0),
		.PLI_PORT    (50000),
		.FIFO_DEPTHS (2)
	) master_0 (
		.clk_clk              (clk_clk),                            //          clk.clk
		.clk_reset_reset      (rst_controller_001_reset_out_reset), //    clk_reset.reset
		.master_address       (master_0_master_address),            //       master.address
		.master_readdata      (master_0_master_readdata),           //             .readdata
		.master_read          (master_0_master_read),               //             .read
		.master_write         (master_0_master_write),              //             .write
		.master_writedata     (master_0_master_writedata),          //             .writedata
		.master_waitrequest   (master_0_master_waitrequest),        //             .waitrequest
		.master_readdatavalid (master_0_master_readdatavalid),      //             .readdatavalid
		.master_byteenable    (master_0_master_byteenable),         //             .byteenable
		.master_reset_reset   (master_0_master_reset_reset)         // master_reset.reset
	);

	nios_pio_0 pio_0 (
		.clk        (clk_clk),                               //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),       //               reset.reset_n
		.address    (mm_interconnect_0_pio_0_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_0_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_0_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_0_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_0_s1_readdata),   //                    .readdata
		.out_port   (pio_0_external_connection_export)       // external_connection.export
	);

	nios_sysid_qsys_0 sysid_qsys_0 (
		.clock    (clk_clk),                                               //           clk.clk
		.reset_n  (~rst_controller_reset_out_reset),                       //         reset.reset_n
		.readdata (mm_interconnect_0_sysid_qsys_0_control_slave_readdata), // control_slave.readdata
		.address  (mm_interconnect_0_sysid_qsys_0_control_slave_address)   //              .address
	);

	nios_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                                  (clk_clk),                                               //                                clk_0_clk.clk
		.master_0_clk_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                        // master_0_clk_reset_reset_bridge_in_reset.reset
		.sysid_qsys_0_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                        // sysid_qsys_0_reset_reset_bridge_in_reset.reset
		.master_0_master_address                        (master_0_master_address),                               //                          master_0_master.address
		.master_0_master_waitrequest                    (master_0_master_waitrequest),                           //                                         .waitrequest
		.master_0_master_byteenable                     (master_0_master_byteenable),                            //                                         .byteenable
		.master_0_master_read                           (master_0_master_read),                                  //                                         .read
		.master_0_master_readdata                       (master_0_master_readdata),                              //                                         .readdata
		.master_0_master_readdatavalid                  (master_0_master_readdatavalid),                         //                                         .readdatavalid
		.master_0_master_write                          (master_0_master_write),                                 //                                         .write
		.master_0_master_writedata                      (master_0_master_writedata),                             //                                         .writedata
		.i2c_Camera_csr_address                         (mm_interconnect_0_i2c_camera_csr_address),              //                           i2c_Camera_csr.address
		.i2c_Camera_csr_write                           (mm_interconnect_0_i2c_camera_csr_write),                //                                         .write
		.i2c_Camera_csr_read                            (mm_interconnect_0_i2c_camera_csr_read),                 //                                         .read
		.i2c_Camera_csr_readdata                        (mm_interconnect_0_i2c_camera_csr_readdata),             //                                         .readdata
		.i2c_Camera_csr_writedata                       (mm_interconnect_0_i2c_camera_csr_writedata),            //                                         .writedata
		.i2c_hdmi_tx_csr_address                        (mm_interconnect_0_i2c_hdmi_tx_csr_address),             //                          i2c_hdmi_tx_csr.address
		.i2c_hdmi_tx_csr_write                          (mm_interconnect_0_i2c_hdmi_tx_csr_write),               //                                         .write
		.i2c_hdmi_tx_csr_read                           (mm_interconnect_0_i2c_hdmi_tx_csr_read),                //                                         .read
		.i2c_hdmi_tx_csr_readdata                       (mm_interconnect_0_i2c_hdmi_tx_csr_readdata),            //                                         .readdata
		.i2c_hdmi_tx_csr_writedata                      (mm_interconnect_0_i2c_hdmi_tx_csr_writedata),           //                                         .writedata
		.pio_0_s1_address                               (mm_interconnect_0_pio_0_s1_address),                    //                                 pio_0_s1.address
		.pio_0_s1_write                                 (mm_interconnect_0_pio_0_s1_write),                      //                                         .write
		.pio_0_s1_readdata                              (mm_interconnect_0_pio_0_s1_readdata),                   //                                         .readdata
		.pio_0_s1_writedata                             (mm_interconnect_0_pio_0_s1_writedata),                  //                                         .writedata
		.pio_0_s1_chipselect                            (mm_interconnect_0_pio_0_s1_chipselect),                 //                                         .chipselect
		.sysid_qsys_0_control_slave_address             (mm_interconnect_0_sysid_qsys_0_control_slave_address),  //               sysid_qsys_0_control_slave.address
		.sysid_qsys_0_control_slave_readdata            (mm_interconnect_0_sysid_qsys_0_control_slave_readdata)  //                                         .readdata
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                 // reset_in0.reset
		.reset_in1      (master_0_master_reset_reset),    // reset_in1.reset
		.clk            (clk_clk),                        //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("none"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.reset_in1      (master_0_master_reset_reset),        // reset_in1.reset
		.clk            (),                                   //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
